version: '3.4'

services:
  postgresql:
    restart: on-failure
    container_name: graphql-db
    image: postgres:14-alpine
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: graphql-password
      POSTGRES_DB: graphql
    ports:
      - '5432:5432'
    volumes:
      - graphql-pgdata:/var/lib/postgresql/data
  api:
    restart: on-failure
    container_name: graphql-api
    depends_on: [postgresql]
    build:
      context: ../graphql-api
      dockerfile: ../graphql-api/.Dockerfile
    ports:
      - '8080:8080'
    command: yarn start:dev
    volumes:
      - ../graphql-api/src:/app/src

  web:
    restart: on-failure
    container_name: graphql_web
    build:
      context: ../graphql-web
      dockerfile: ../graphql-web/.Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ../graphql-web/src:/app/src

volumes:
  graphql-pgdata:
    driver: local